### ISSUE TITLE
parametricky konstruktor

### ISSUE THREAD

**Issue by MartinParak** [LadislavJuhasz/Oko#1]
https://github.com/LadislavJuhasz/Oko/blob/10c18981f143782d8ff58b36f745be55b04883a3/model/CardFactory.java#L20

Tento konstruktor potrebujes?

**Comment by MartinParak** [comment]
metodu, nie konstruktor.

**Comment by LadislavJuhasz** [comment]
Poznamenané; nateraz je to @Deprecated, neskôr to zrejme vymažem.
