### ISSUE TITLE
parametricky konstruktor

### ISSUE THREAD

**Issue by MartinParak** [LadislavJuhasz/Oko#2]
https://github.com/LadislavJuhasz/Oko/blob/10c18981f143782d8ff58b36f745be55b04883a3/model/CardFactory.java#L24

Tento konstruktor budes potrebovat? Lebo ak nie, tak je tu zbytocny. Karta s farbou, ale bez hodnoty.

**Comment by MartinParak** [comment]
Pardon, nie parametricky konstruktor, ale factory metodu

**Comment by LadislavJuhasz** [comment]
Poznamenané; nateraz je to @Deprecated, neskôr to zrejme vymažem.
